WORDS = {
    "Beginner": [
        ("cat", "кот"), ("dog", "собака"), ("house", "дом"), ("water", "вода"),
        ("book", "книга"), ("table", "стол"), ("chair", "стул"), ("window", "окно"),
        ("door", "дверь"), ("car", "машина"), ("food", "еда"), ("friend", "друг"),
        ("family", "семья"), ("school", "школа"), ("work", "работа"), ("day", "день"),
        ("night", "ночь"), ("morning", "утро"), ("city", "город"), ("street", "улица"),
        ("red", "красный"), ("blue", "синий"), ("big", "большой"), ("small", "маленький"),
        ("good", "хороший"), ("bad", "плохой"), ("happy", "счастливый"), ("sad", "грустный"),
        ("eat", "есть"), ("drink", "пить"), ("sleep", "спать"), ("run", "бежать"),
        ("walk", "идти"), ("talk", "говорить"), ("name", "имя"), ("time", "время"),
    ],
    "Elementary": [
        ("weather", "погода"), ("season", "сезон"), ("travel", "путешествие"), ("airport", "аэропорт"),
        ("ticket", "билет"), ("hotel", "отель"), ("restaurant", "ресторан"), ("menu", "меню"),
        ("waiter", "официант"), ("kitchen", "кухня"), ("bedroom", "спальня"), ("garden", "сад"),
        ("neighbor", "соседи"), ("village", "деревня"), ("country", "страна"), ("language", "язык"),
        ("question", "вопрос"), ("answer", "ответ"), ("problem", "проблема"), ("solution", "решение"),
        ("decide", "решать"), ("believe", "верить"), ("remember", "помнить"), ("forget", "забывать"),
        ("explain", "объяснять"), ("understand", "понимать"), ("learn", "учить"), ("teach", "преподавать"),
        ("important", "важный"), ("difficult", "трудный"), ("easy", "лёгкий"), ("interesting", "интересный"),
        ("boring", "скучный"), ("expensive", "дорогой"), ("cheap", "дешёвый"), ("dangerous", "опасный"),
    ],
    "Intermediate": [
        ("achieve", "достигать"), ("opportunity", "возможность"), ("environment", "окружающая среда"), ("government", "правительство"),
        ("economy", "экономика"), ("society", "общество"), ("culture", "культура"), ("tradition", "традиция"),
        ("behavior", "поведение"), ("attitude", "отношение"), ("relationship", "отношения"), ("communication", "общение"),
        ("responsibility", "ответственность"), ("experience", "опыт"), ("knowledge", "знание"), ("skill", "навык"),
        ("improve", "улучшать"), ("develop", "развивать"), ("increase", "увеличивать"), ("decrease", "уменьшать"),
        ("influence", "влиять"), ("affect", "влиять"), ("consider", "рассматривать"), ("suggest", "предлагать"),
        ("require", "требовать"), ("provide", "предоставлять"), ("achieve", "достигать"), ("avoid", "избегать"),
        ("encourage", "поощрять"), ("prevent", "предотвращать"), ("succeed", "добиваться успеха"), ("fail", "проваливаться"),
        ("various", "различный"), ("similar", "похожий"), ("particular", "конкретный"), ("significant", "значительный"),
    ],
    "Upper-Intermediate": [
        ("inevitable", "неизбежный"), ("ambiguous", "неоднозначный"), ("controversial", "спорный"), ("consequence", "последствие"),
        ("circumstance", "обстоятельство"), ("perspective", "точка зрения"), ("assumption", "предположение"), ("evidence", "доказательство"),
        ("argument", "аргумент"), ("contradiction", "противоречие"), ("phenomenon", "явление"), ("hypothesis", "гипотеза"),
        ("emphasize", "подчёркивать"), ("undermine", "подрывать"), ("enhance", "усиливать"), ("acquire", "приобретать"),
        ("contribute", "вносить вклад"), ("compensate", "компенсировать"), ("compromise", "компромисс"), ("negotiate", "вести переговоры"),
        ("substantial", "существенный"), ("comprehensive", "всеобъемлющий"), ("sustainable", "устойчивый"), ("efficient", "эффективный"),
        ("reliable", "надёжный"), ("consistent", "последовательный"), ("flexible", "гибкий"), ("vulnerable", "уязвимый"),
        ("inevitable", "неизбежный"), ("subtle", "тонкий, неявный"), ("profound", "глубокий"), ("ambitious", "амбициозный"),
        ("reluctant", "неохотный"), ("eager", "стремящийся"), ("curious", "любопытный"),
    ],
    "Advanced": [
        ("ubiquitous", "повсеместный"), ("paradigm", "парадигма"), ("dichotomy", "дихотомия"), ("nuance", "нюанс"),
        ("scrutinize", "тщательно изучать"), ("ameliorate", "улучшать"), ("exacerbate", "усугублять"), ("mitigate", "смягчать"),
        ("juxtapose", "сопоставлять"), ("perpetuate", "увековечивать"), ("relinquish", "отказываться"), ("reconcile", "примирять"),
        ("intricate", "сложный, замысловатый"), ("elusive", "неуловимый"), ("pragmatic", "практичный"), ("plausible", "правдоподобный"),
        ("arbitrary", "произвольный"), ("coherent", "связный"), ("redundant", "избыточный"), ("meticulous", "тщательный"),
        ("resilient", "стойкий"), ("versatile", "разносторонний"), ("autonomous", "автономный"), ("indispensable", "незаменимый"),
        ("inherent", "присущий"), ("conducive", "способствующий"), ("detrimental", "пагубный"), ("formidable", "грозный, внушительный"),
        ("notwithstanding", "несмотря на"), ("albeit", "хотя"), ("henceforth", "отныне"), ("nonetheless", "тем не менее"),
        ("discrepancy", "несоответствие"), ("inception", "начало"), ("culmination", "завершение"),
    ],
    "Proficient": [
        ("ephemeral", "эфемерный"), ("serendipity", "счастливая случайность"), ("idiosyncrasy", "особенность"), ("equanimity", "невозмутимость"),
        ("magnanimous", "великодушный"), ("ostentatious", "показной"), ("surreptitious", "тайный"), ("perfunctory", "поверхностный"),
        ("vicissitude", "превратность судьбы"), ("obfuscate", "затемнять смысл"), ("vindicate", "оправдывать"), ("acquiesce", "соглашаться"),
        ("circumvent", "обходить"), ("debilitate", "ослаблять"), ("exacting", "требовательный"), ("fastidious", "разборчивый"),
        ("garrulous", "болтливый"), ("hapless", "невезучий"), ("incessant", "непрестанный"), ("laconic", "лаконичный"),
        ("mellifluous", "мелодичный"), ("nebulous", "туманный"), ("obstinate", "упорный"), ("paucity", "скудость"),
        ("quintessential", "типичный, образцовый"), ("recalcitrant", "непокорный"), ("sycophant", "подхалим"), ("tenacious", "упорный"),
        ("ubiquity", "повсеместность"), ("vexatious", "досадный"), ("zealous", "ревностный"), ("aberration", "отклонение от нормы"),
        ("benevolent", "благожелательный"), ("capricious", "капризный"), ("deference", "почтение"),
    ],
}

LEVELS_ORDER = ["Beginner", "Elementary", "Intermediate", "Upper-Intermediate", "Advanced", "Proficient"]
